/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/
package basicimplementation.findthedifference;

public class Solution {
    public char findTheDifference(String s, String t) {
        int sumT = 0;
        int sumS = 0;
        int diff = 0;

        for (int i = 0; i < t.length(); i++) {
            sumT += t.charAt(i);
        }

        for (int i = 0; i < s.length(); i++) {

            sumS += s.charAt(i);
        }
        diff = sumT - sumS;
        return (char) diff;
    }

    public static void main(String[] args) {
        Solution sol = new Solution();
        char output = sol.findTheDifference("abcd", "abcfd");
        System.out.println(output);
    }
}